// значения нужны только для отладки через console.log, когда выводятся присвоенные цифры це неудобно

export const enum EventType {
    // page
    INIT_PAGE_REQUEST = 'INIT_PAGE_REQUEST',
    INIT_COUNTRY_PAGE_REQUEST = 'INIT_COUNTRY_PAGE_REQUEST',
    INIT_REGISTER_PAGE_REQUEST = 'INIT_REGISTER_PAGE_REQUEST',
    INIT_LOGIN_PAGE_REQUEST = 'INIT_LOGIN_PAGE_REQUEST',
    INIT_SIGHT_PAGE_REQUEST = 'INIT_SIGHT_PAGE_REQUEST',
    INIT_TRIP_PAGE_REQUEST = 'INIT_TRIP_PAGE_REQUEST',
    INIT_ERROR_PAGE_REQUEST = 'INIT_ERROR_PAGE_REQUEST',
    DESTROY_CURRENT_PAGE_REQUEST = 'DESTROY_CURRENT_PAGE_REQUEST',
    // header
    REMOVE_HEADER_REQUEST = 'REMOVE_HEADER_REQUEST',
    SET_MAIN_HEADER_REQUEST = 'SET_MAIN_HEADER_REQUEST',
    SET_MAIN_HEADER_LOGGED_RESPONSE = 'SET_MAIN_HEADER_LOGGED_RESPONSE',
    SET_MAIN_HEADER_BASIC_RESPONSE = 'SET_MAIN_HEADER_BASIC_RESPONSE',
    SET_MAIN_HEADER_EMPTY_RESPONSE = 'SET_MAIN_HEADER_EMPTY_RESPONSE',
    // country
    GET_COUNTRY_REQUEST = 'GET_COUNTRY_REQUEST',
    GET_COUNTRY_RESPONSE = 'GET_COUNTRY_RESPONSE',
    // INIT_COUNTRY_REQUEST,
    // INIT_COUNTRY_RESPONSE,
    GET_COUNTRY_CARDS_REQUEST = 'GET_COUNTRY_CARDS_REQUEST',
    GET_COUNTRY_CARDS_RESULT = 'GET_COUNTRY_CARDS_RESULT',
    GET_COUNTRY_CARDS_ERROR = 'GET_COUNTRY_CARDS_ERROR',
    // auth
    SUBMIT_LOGIN_DATA = 'SUBMIT_LOGIN_DATA',
    SET_VALIDATION_ERROR_LOGIN = 'SET_VALIDATION_ERROR_LOGIN',
    SUBMIT_REGISTER_DATA = 'SUBMIT_REGISTER_DATA',
    SET_VALIDATION_ERROR_REGISTER = 'SET_VALIDATION_ERROR_REGISTER',
    // sight
    GET_SIGHT_REQUEST = 'GET_SIGHT_REQUEST',
    GET_SIGHT_RESPONSE = 'GET_SIGHT_RESPONSE',
    // trip
    GET_TRIP_REQUEST = 'GET_TRIP_REQUEST',
    GET_TRIP_RESPONSE = 'GET_TRIP_RESPONSE',
    // profile
    INIT_PROFILE_REQUEST = 'INIT_PROFILE_REQUEST',
    GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST',
    GET_PROFILE_RESPONSE = 'GET_PROFILE_RESPONSE',
    UPDATE_PROFILE_METADATA_REQUEST = 'UPDATE_PROFILE_METADATA_REQUEST',
    UPDATE_PROFILE_PHOTO_REQUEST = 'UPDATE_PROFILE_PHOTO_REQUEST'
}
