import { backendEndpoint, backendFileEndpoint, frontEndEndPoint } from './endpoints';
import {
	loginURI,
	registerURI,
	countrySights,
	profile,
	logout,
	sightURI,
	sightsURI,
	tripURI,
	reviewsURI,
	reviewURI,
	queryParamsToGetReview,
	upload,
	postTripURI,
	listOfCountries,
	tripCoord,
} from './uris';
import { russiaFormName, russiaUriName, nicaraguaFormName, nicaraguaUriName } from './defaults';
import { pathsURLfrontend, paramsURLfrontend } from '@/constants/frontendURIs';

export {
	sightURI,
	sightsURI,
	tripURI,
	tripCoord,
	backendEndpoint,
	backendFileEndpoint,
	loginURI,
	registerURI,
	russiaFormName,
	countrySights,
	russiaUriName,
	profile,
	logout,
	nicaraguaFormName,
	nicaraguaUriName,
	reviewsURI,
	reviewURI,
	pathsURLfrontend,
	paramsURLfrontend,
	queryParamsToGetReview,
	upload,
	postTripURI,
	frontEndEndPoint,
	listOfCountries,
};
